title: Towarzystwo Psychopedagogiczne
description: >- # this means to ignore newlines until "baseurl:"
  Profesjonalne wsparcie psychologiczne i pedagogiczne dla dzieci, młodzieży i dorosłych w Bolesławcu i online. Jesteśmy tu, by Ci pomóc.
baseurl: "/nazwa-twojego-repozytorium" # ZMIEŃ NA NAZWĘ SWOJEGO REPOZYTORIUM
url: "https://psychopedagog.org" # the base hostname & protocol for your site, e.g. http://example.com

# Definiowanie kolekcji dla postów w różnych językach
collections:
  posts_pl:
    output: true
    permalink: /blog/:slug/
  posts_en:
    output: true
    permalink: /en/blog/:slug/

# Domyślne ustawienia dla kolekcji
defaults:
  - scope: { path: "", type: "posts_pl" }
    values: { layout: "post", lang: "pl" }
  - scope: { path: "", type: "posts_en" }
    values: { layout: "post", lang: "en" }